<?php

/**
 * @file
 * Contains genealogy_date.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function genealogy_date_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the genealogy_date module.
    case 'help.page.genealogy_date':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Field to store dates for Genealogical purposes') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function genealogy_date_theme() {
  return [
    'genealogy_date' => [
      'render element' => 'children',
    ],
  ];
}
