<?php

/**
 * @file
 * Contains genealogy_setup.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function genealogy_setup_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the genealogy_setup module.
    case 'help.page.genealogy_setup':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Setup module for Genealogy package') . '</p>';
      return $output;

    default:
  }
}
