<?php

/**
 * @file
 * Contains genealogy_notes.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function genealogy_notes_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the genealogy_notes module.
    case 'help.page.genealogy_notes':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Research notes for Genealogy entities') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function genealogy_notes_theme() {
  return [
    'genealogy_notes' => [
      'render element' => 'children',
    ],
  ];
}
